### ISSUE TITLE
Creating document for system game designing

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/tinker2d#2]
Hi! 

Can you create document for system game designing? As example you can use a book "Introduction to Game Systems Design" by Dax Gazaway. Also we can discuss some ideas about game mechanics or characteristics so theу will be a list to work with as soon as you ready.

**Comment by KonstantinKlepikov** [comment]
@chemeshuggah [link](https://docs.google.com/document/d/1AlZTKOATSG7BKikuziwBkrrk-qQYob__AIs5H0M3LvU/edit)
